FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5199

ENV ASPNETCORE_URLS=http://+:5199

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["DotnetCalendar/DotnetCalendar.csproj", "DotnetCalendar/"]
RUN dotnet restore "DotnetCalendar/DotnetCalendar.csproj"
COPY . .
WORKDIR "/src/DotnetCalendar"
RUN dotnet build "DotnetCalendar.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "DotnetCalendar.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DotnetCalendar.dll"]
