services:
  dotnetcalendar:
    image: dotnetcalendar
    build:
      context: ./dotnet-calendar
      dockerfile: DotnetCalendar/Dockerfile
    ports:
      - 5199:5199
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
  reactcalendar:
    image: reactcalendar
    build:
      context: ./react-calendar
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./react-calendar/src
          target: /usr/src/app/src
  mongo:
    image: mongo
    restart: always
