# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dotnetcalendar:
    image: dotnetcalendar
    build:
      context: .
      dockerfile: DotnetCalendar/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5199:5199
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
